[package]
name = "onc-rpc-xdr"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Shared XDR serialization and deserialization support for generated ONC RPC code."

[dependencies]
bytes.workspace = true
thiserror.workspace = true
