[package]
name = "onc-rpc-tls"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "TLS and STARTTLS integration points for ONC RPC."

[dependencies]
async-trait.workspace = true
bytes.workspace = true
rustls.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
onc-rpc-runtime = { version = "0.1.0", path = "../onc-rpc-runtime" }
onc-rpc-server = { version = "0.1.0", path = "../onc-rpc-server" }
onc-rpc-wire = { version = "0.1.0", path = "../onc-rpc-wire" }

[dev-dependencies]
onc-rpc-xdr = { version = "0.1.0", path = "../onc-rpc-xdr" }
rcgen.workspace = true
