[package]
name = "onc-rpc-tls"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "TLS and STARTTLS integration points for ONC RPC."

[dependencies]
thiserror.workspace = true

