[package]
name = "onc-rpc-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Authentication types and helpers for ONC RPC clients and servers."

[dependencies]
bytes.workspace = true
thiserror.workspace = true
onc-rpc-wire = { version = "0.1.0", path = "../onc-rpc-wire" }
onc-rpc-xdr = { version = "0.1.0", path = "../onc-rpc-xdr" }
