[package]
name = "time-service-example"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[dependencies]
tokio.workspace = true
onc-rpc-runtime = { version = "0.2.0", path = "../../crates/onc-rpc-runtime" }
onc-rpc-server = { version = "0.2.0", path = "../../crates/onc-rpc-server" }
onc-rpc-xdr = { version = "0.2.0", path = "../../crates/onc-rpc-xdr" }
