[package]
name = "onc-rpc-gen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Core code generation for XDR types and ONC RPC client/server stubs."

[lib]
name = "onc_rpcgen"

[[bin]]
name = "onc-rpcgen"
path = "src/main.rs"

[dependencies]
clap.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_cmd = "2.0"
async-trait.workspace = true
bytes.workspace = true
onc-rpc-auth = { version = "0.2.0", path = "../onc-rpc-auth" }
onc-rpc-runtime = { version = "0.2.0", path = "../onc-rpc-runtime" }
onc-rpc-server = { version = "0.2.0", path = "../onc-rpc-server" }
onc-rpc-xdr = { version = "0.2.0", path = "../onc-rpc-xdr" }
predicates = "3.1"
tempfile = "3.23"
tokio.workspace = true
